name: Metrics
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: metrics.svg
          committer_message: 'chore: update ${filename}'
          config_timezone: Asia/Ho_Chi_Minh
          template: terminal
          base: header, activity, repositories, metadata
          config_order: base.header, base.repositories, isocalendar, music
          output_condition: skip-if-only-metadata-changed
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage

  delete-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 2
          keep_minimum_runs: 2
